# US ACCIDENTE 2016 - 2021

Grupo: Manuel Pereda y Clara Thays

El archivo original esta en: https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents

# EDA - 1. Ingesta y Procesado Inicial

In [1]:
import pandas as pd

Lectura de datos

In [2]:
accidentes = pd.read_csv("US_Accidents_Dec21_updated.csv")

In [3]:
accidentes.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,40.112060,-83.031870,3.230,Between Sawmill Rd/Exit 20 and OH-315/Olentang...,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.865420,-84.062800,39.865010,-84.048730,0.747,At OH-4/OH-235/Exit 41 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Night
2,A-3,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.102660,-84.524680,39.102090,-84.523960,0.055,At I-71/US-50/Exit 1 - Accident.,...,False,False,False,False,False,False,Night,Night,Night,Day
3,A-4,2,2016-02-08 06:51:45,2016-02-08 12:51:45,41.062130,-81.537840,41.062170,-81.535470,0.123,At Dart Ave/Exit 21 - Accident.,...,False,False,False,False,False,False,Night,Night,Day,Day
4,A-5,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,39.170476,-84.501798,0.500,At Mitchell Ave/Exit 6 - Accident.,...,False,False,False,False,False,False,Day,Day,Day,Day

In [4]:
accidentes.dtypes

ID                        object
Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description               object
Number                   float64
Street                    object
Side                      object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Weather_Timestamp         object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object

**Eliminado de datos**

Eliminamos las columnas consideramos que no aportan valor para el anÃ¡lisis 

1. End Lat
2. End Lng
3. Description
4. Number
5. Zipcode
6. Country (Son todas en el USA)
7. Timezone
8. Airport Code
9. Weather Timestap
10. Wind Direction
11. Nautical Twilight
12. Astronomical Twilight

In [5]:
accidentes = accidentes.drop(["End_Lat" , "End_Lng", "Description", "Number", "Zipcode" ],axis = 1)

In [6]:
accidentes = accidentes.drop(["Country","Timezone", "Airport_Code", "Weather_Timestamp", "Wind_Direction","Nautical_Twilight" ,"Astronomical_Twilight"],axis = 1)

In [7]:
accidentes.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Street,Side,City,...,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight
0,A-1,3,2016-02-08 00:37:08,2016-02-08 06:37:08,40.108910,-83.092860,3.230,Outerbelt E,R,Dublin,...,False,False,False,False,False,False,False,False,Night,Night
1,A-2,2,2016-02-08 05:56:20,2016-02-08 11:56:20,39.865420,-84.062800,0.747,I-70 E,R,Dayton,...,False,False,False,False,False,False,False,False,Night,Night
2,A-3,2,2016-02-08 06:15:39,2016-02-08 12:15:39,39.102660,-84.524680,0.055,I-75 S,R,Cincinnati,...,False,False,False,False,False,False,False,False,Night,Night
3,A-4,2,2016-02-08 06:51:45,2016-02-08 12:51:45,41.062130,-81.537840,0.123,I-77 N,R,Akron,...,False,False,False,False,False,False,False,False,Night,Night
4,A-5,3,2016-02-08 07:53:43,2016-02-08 13:53:43,39.172393,-84.492792,0.500,I-75 S,R,Cincinnati,...,False,False,False,False,False,False,False,False,Day,Day

In [8]:
accidentes.to_csv("accidentes.1.procesado_inicial.csv", index = False)